import userAvatar from '../assets/images/user.png'

export const DataList = [
  {
    id: 1,
    name: 'Amit',
    msg: 'bring your photo',
    avatar: '',
    dateTime: '3h ago',
  },
  {
    id: 2,
    name: 'Rohit',
    msg: 'bring your photo',
    avatar: userAvatar,
    dateTime: '5h ago',
  },
  {
    id: 3,
    name: 'SIT guys',
    msg: 'bring your photo',
    avatar: userAvatar,
    dateTime: '6h ago',
  },
  {
    id: 4,
    name: 'Music group',
    msg: 'bring your photo',
    avatar: '',
    dateTime: '7h ago',
  },
  {
    id: 5,
    name: 'Akash',
    msg: 'bring your photo',
    avatar: userAvatar,
    dateTime: '2h ago',
  },
  {
    id: 6,
    name: 'Rohan',
    msg: 'bring your photo',
    avatar: '',
    dateTime: '5h ago',
  },
  {
    id: 7,
    name: 'Music group',
    msg: 'bring your photo',
    avatar: userAvatar,
    dateTime: '7h ago',
  },
  {
    id: 8,
    name: 'Akash',
    msg: 'bring your photo',
    avatar: userAvatar,
    dateTime: '2h ago',
  },
  {
    id: 9,
    name: 'Rohan',
    msg: 'bring your photo',
    avatar: '',
    dateTime: '5h ago',
  },
  {
    id: 10,
    name: 'Rohan',
    msg: 'bring your photo',
    avatar: userAvatar,
    dateTime: '5h ago',
  },
  {
    id: 11,
    msg: 'bring your photo',
    name: 'Music group',
    avatar: userAvatar,
    dateTime: '7h ago',
  },
  {
    id: 12,
    name: 'Akash',
    msg: 'bring your photo',
    avatar: userAvatar,
    dateTime: '2h ago',
  },
  {
    id: 13,
    name: 'Rohan',
    msg: 'bring your photo',
    avatar: '',
    dateTime: '5h ago',
  },
]
